[functions]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/ncip/:splat"
[[redirects]]
  force = true
  from = "/proxy/*"
  status = 200
  to = "/.netlify/functions/tibhidproxy/:splat"
[build]
  command = "echo No build needed"